development:
  adapter: postgresql
  encoding: unicode
  database: autostitch_tutorial_development
  host: localhost
  pool: 5
  username: efatsi
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: autostitch_tutorial_test
  pool: 5
  username: efatsi
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: autostitch_tutorial_production
  pool: 5
  username: efatsi
  password:
